import React from 'react'

export const AboutMe = () => {
    return <div>
        <div>
        Heena Gupta is an Engineering Manager at Expedia, leading Flights price tracking and predictions across web, iOS, and Android, alongside operational excellence for quality across multiple organisations. She is also a service owner for flight progressive web applications. Heena completed her Bachelor of Technology in Computer Engineering from Delhi Technological University (2011–2015). She enjoys coding, learning new technologies, and mentoring junior engineers.
Heena began contributing to open source early in her career through KDE, the open-source community behind K Desktop Environment related projects. As a Season of KDE (2012) student developer, she learned globally adopted engineering best practices through community collaboration. In 2013, she was selected as a Google Summer of Code student developer, where she contributed to the KDE Plasma team and played a key role in revamping plasmoid applications. She later strengthened the community by mentoring new contributors as a Google Code-In mentor (2013), and served as a co-administrator and mentor for Season of KDE (2014) and Google Code-In (2014). She has represented KDE in Google Summer of Code knowledge-sharing sessions at DTU, presented KDE Plasma projects at FOSSASIA 2015 (Singapore), and her open-source contributions have been featured on the Google Open Source Blog.
With over ten years of industry experience, Heena has worked across both startups and large organisations, including Paytm, Shipsy, Indus Valley Partners, and Expedia. She is passionate about working on diverse problem spaces and continuously expanding her skill set. As a speaker, she recently presented “Search Speed: Making Expedia Flights Faster” at JSNation 2024 (Amsterdam) and React Summit US 2024, and has also participated in panel discussions on growth paths for frontend developers. Previously, she presented “Portfolio Management through storytelling using narrative visualizations with advanced filtering” at the Hong Kong Open Source Conference (2017), and shared related work through a poster presentation at Grace Hopper Conference India (2017). She has also mentored aspiring female developers through Learn IT, Girl (2015), encouraging contributions to open-source communities such as KDE.
Through her engineering leadership, open-source contributions, and consistent mentorship, Heena is creating meaningful impact in technology while actively supporting diversity, inclusion, and the growth of the next generation of engineers.

 
        </div>
    </div>
}